- Cargo.lock
- Cargo.toml
- src/directsketch.rs
with the semaphore permitting limiting the total number of downloads to 3 concurrent, we don't need to do the delay anymore.
> remove interval delay

- Cargo.lock
- Cargo.toml
- src/directsketch.rs
- tests/test_gbsketch.py
- In v0.2.1, if we encounter an issue with the md5sum file download, the error handling loop would cause us to hang / not continue to process sigs.
- This fixes the issue by introducing an `error_handler` to receive errors and notify as we go.
- because we can't `bail` from within the `error_handler`, I introduce and AtomicBool to monitor whether we need to `bail` because we expected sigs but didn't end up writing any
I just ran this on 95k protein downloads, and it took 2h54mins and 12MB (!?) of RAM
```
cat /home/ntpierce/database-releases/gtdb-rs214.protein/logs/gtdb-rs214.protein.download_and_sketch_missing.benchmark
s	h:m:s	max_rss	max_vms	max_uss	max_pss	io_in	io_out	mean_load	cpu_time
10476.4868	2:54:36	445.03	12946.43	456.79	457.60	86.62	25.43	1.27	133.17
```
> fix error handling

- src/directsketch.rs
This PR reverts the channel size, which I was starting to test while updating for 0.2.2 but didn't get around to benchmarking. 
I think -- channel size = the number of items collection prior to action, e.g. size 4 means 4 sigs are stored in the channel before they're written. So increasing channel size means you write larger batches at a single time. The more sigs we're storing at once, the more memory we'll require.
Seems like the timing is variable (perhaps depending on whatever else is happening on farm?), but not consistently faster for one or the other. Since smaller channel size will requires less memory, let's keep it small.
this branch, 9 accs:
```
Command being timed: "sourmash scripts gbsketch update.20240503-fungi.head10.csv -o test10.zip --failed test10.failed.csv -r 1 …
```
> revert channel sizes

- src/directsketch.rs
- tests/test_gbsketch.py
- fixes #26 
If we're not keeping fastas, avoid downloading genome or proteome files unnecessarily by setting `genomes_only` or `proteomes_only` from the sketch params. Notify the user of this behavior.
> also set genomes-only/proteomes-only via params if not keeping fastas

- src/directsketch.rs
- tests/test_gbsketch.py
- mostly fixes #35. To finish, enable reading failure file as `urlsketch` input in #34.
Changes:
- `url.as_str()` prior to printing
- test output format of failed file
> fix url printing

- README.md
- pyproject.toml
- src/directsketch.rs
- src/lib.rs
- src/python/sourmash_plugin_directsketch/__init__.py
- src/utils.rs
- tests/test-data/acc-url.csv
- tests/test_gbsketch.py
- tests/test_urlsketch.py
`urlsketch` for downloading from any url, rather than just the genbank assembly datasets (`gbsketch`)
Notes:
- changes failure output format slightly! the new header is: `accession,name,moltype,md5sum,download_filename,url`, which matches the `urlsketch` input format.
- fixes #20
> add `urlsketch` command

- Cargo.lock
- Cargo.toml
Update to sourmash-rs core r0.14.0, which includes https://github.com/sourmash-bio/sourmash/pull/3193.
Fixes https://github.com/sourmash-bio/sourmash_plugin_directsketch/issues/49
> MRG: update to sourmash-rs core r0.14.0

- .github/workflows/build-test.yml
`Mambaforge` is being sunset, all workflows should switch to `Miniforge`
https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/
> MRG: fix ci by moving install from `mambaforge` --> `miniforge`

- src/directsketch.rs
- tests/test_gbsketch.py
- fixes #118 
This restores use of an output zipfile that does not contain an explicit path:`output.zip` was previously failing, but not `/path/to/output.zip`, which is why all tests passed.
Since we use tempdirs to run tests, not sure how to test this appropriately...?
> MRG: fix bug in zip paths if output provided in current dir

- src/directsketch.rs
- src/python/sourmash_plugin_directsketch/__init__.py
- tests/test_gbsketch.py
- tests/test_urlsketch.py
Give output when we finish each batch, rather than when we start writing the manifest. Also improve the final location reporting for batched files.
- fixes #175
> MRG: batched zip reporting - notify after finishing batch to be clearer

- src/python/sourmash_plugin_directsketch/__init__.py
- tests/test_gbsketch.py
- tests/test_urlsketch.py
Fixes https://github.com/sourmash-bio/sourmash_plugin_directsketch/issues/192
`--failed` defaults to `os.path.basename(csv_file).fail.txt`, and `--checksum-fail` defaults to `os.path.basename(csv_file).checksum_fail.txt`.
> MRG: provide default failed filenames based on CSV

- src/utils/mod.rs
- tests/test-data/acc-bad-header-order.csv
- tests/test_gbsketch.py
Fixes https://github.com/sourmash-bio/sourmash_plugin_directsketch/issues/187
TODO:
> MRG: ignore extra columns in gbsketch input CSV

- Cargo.lock
- Cargo.toml
- README.md
- src/directsketch.rs
- src/lib.rs
- src/python/sourmash_plugin_directsketch/__init__.py
- src/utils/mod.rs
- tests/test_gbsketch.py
This PR enables processing directly on the stream (`gbsketch` only here), meaning we do not have to download the entire file prior to processing! This should reduce memory requirements, since we no longer need to hold full genomes in memory. 
Other internal changes:
- We now read gbsketch input directly to an `AccessionData` struct, rather than having a separate bespoke struct for `gbsketch`. We also use `AccessionData` directly instead of building a `FailedDownload`. These changes simplify processing and will better enable code reuse between `gbsketch` and `urlsketch`.
- After finding the fetch urls via the dehydrated file, we then add them to the `AccessionData` structs and use `stream_and_process_with_retry` to stream and save/sketch the data. This function should be reusable for …
> MRG: `gbsketch` streaming processing

- src/directsketch.rs
- src/utils/mod.rs
- tests/test_urlsketch.py
> MRG: streaming `urlsketch` processing

- src/directsketch.rs
Now that we're using the same processing functions (again), refactor and clean up all the rest of the code reused between `gbsketch` and `urlsketch`
> MRG: Consolidate reused code across `gbsketch`/`urlsketch`

- README.md
- src/directsketch.rs
- src/lib.rs
- src/python/sourmash_plugin_directsketch/__init__.py
- tests/test_gbsketch.py
- tests/test_urlsketch.py
- Restores proper moltype FASTA filtering via `--genomes-only` and `--proteomes-only` for `--keep-fasta`. We must have lost this in the recent refactor. Adds tests for these cases.
- Improves batched restart for `--keep-fasta` by avoiding redownloading and overwriting fastas. This works because we now mark incomplete fasta files with `.incomplete` and only rename when finished (so we can ~trust that properly-named fasta files are complete).
- Adds `--no-overwrite-fasta` to allow avoiding overwriting even if not batching (automatically turned on with batching).
- Adds reporting re: # skipped due to moltype exclusion, existing sigs and/or fasta, and (for gbsketch only, missing URLs).
- Make sure we don't read existing sig batches if not using batching (`--batch-size`)
- update docs to …
> MRG: optionally avoid re-downloading existing FASTA when using `--keep-fasta`

- Cargo.lock
- Cargo.toml
- README.md
- pyproject.toml
- bump directsketch version
- pin rust to match sourmash to prevent dependabot from using a newer rust version and updating the version of the Cargo.lock file
> MRG: upd version to 0.6.0; pin rust to 1.74

- README.md
- src/python/sourmash_plugin_directsketch/__init__.py
- Since we now set a default for `--n-simultaneous-downloads`, it should never be `None` and the limitation code based on NCBI API Key should never trigger. But let's clean it up - it's no longer needed.
- The help for `--n-simultaneous-downloads` includes outdated guidance on memory limitation. Remove.
> MRG: update help for simultaneous downloads; clean up prior `n` limitation code

- src/directsketch.rs
- tests/test_gbsketch.py
- tests/test_urlsketch.py
Adds explicit checks for `SIGTERM`, as would be sent via slurm/snakemake+slurm. Adds tests for catching sigterm.
When we get a shutdown request (ctrl-C or sigterm), we don't shut down immediately. Instead, we cancel each process as they get to a stop check (these are frequent, e.g. each chunk during file download) so we don't leave any spawned processes running. After that, we will exit out to the main loop and enter into the `cancel_token.is_cancelled()` at the end, meaning we exit via `bail` (exit code 1).
- fixes #242
> MRG: add explicit sigterm handling

- src/directsketch.rs
- tests/test_gbsketch.py
Previously, we were writing the download failures for missing `gbsketch` URLs (fetch links we could not find in the dehydrated zipfile) inside of the `for accinfo` loop, meaning we wrote each multiple times. This PR moves the writing code outside of the loop to avoid duplicated failure writing.
- fixes #240
> MRG: fix duplicated failure writing for missing gbsketch URLs

- tests/test_gbsketch.py
- tests/test_urlsketch.py
Replace `sourmash.load_one_signature` with `sourmash.signature.load_one_signature_from_json`
> MRG: fix deprecations (rm use of `sourmash.load_one_signature`)

- Cargo.lock
- README.md
- src/directsketch.rs
- src/lib.rs
- src/python/sourmash_plugin_directsketch/__init__.py
- tests/test_gbsketch.py
- tests/test_urlsketch.py
This PR fixes the two issues described in #248.
- First, we add a new option, `--allow-completed`. This will allow snakemake to think that abatched workflow succeeded, even if no new signatures were written **as long as we find some existing signatures in the batches**. This will likely be most useful when restarting batches, as if there are only _failing_ entries left, there will be no signatures to write. Note that you will then want to go back and look at the failures csv file to make sure those are truly failures (and if not, to retry building those separately).
- Second, we add a new output for batching, the batchlist file. This file will be "{output}.batchlist.txt", so if you're writing sigs to `simple.zip`, this will be `simple.zip.batchlist.txt`. This will contain all batches …
> MRG: optionally allow empty sig zips; write list of batch outputs to file
